{
  "services": [
    {
      "type": "web",
      "name": "netflix-gol",
      "env": "node",
      "region": "oregon",
      "plan": "free",
      "buildCommand": "npm install",
      "startCommand": "npm start",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        }
      ]
    }
  ]
}
